#! /bin/bash
#DIR=`date +%d-%m-%y+%r`
currentDate=`date`
echo $currentDate





#! /bin/bash
export access_key= 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
git clone https://vishnureddy997:$access_key@github.com/vishnureddy997/test11.git
sudo docker build -t te3 .
sudo docker run -dt -p 80:80  --name  tes2  te3
sudo docker cp test11/Dockerfile tes1:/tmp




